name: Build and Push to Docker Hub (Production)

on:
  push:
    tags:
      - 'prod*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Git Tag
        run: echo "GIT_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      # Checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      # Log into Docker Hub
      - name: Log into registry
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: 'Build Docker image and push to registry'
        env: 
            IMAGE_TAG: ${{ env.GIT_TAG }}
        run: | 
          docker build MHC-ACS --file MHC-ACS/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/mhc-acs-ai:$IMAGE_TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/mhc-acs-ai:$IMAGE_TAG
